---
repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint
        name: Run yamllint
        description: Lint yaml files
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.31.1
    hooks:
      - id: markdownlint
        name: Run markdownlint
        description: Lint markdown files
  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.10.2
    hooks:
      - id: markdown-link-check
        name: Run markdown-link-check
        description: Check link in markdown files
        args: [-a, "200,206,403,429"]
