---
site_name: Notes
site_description: My notes on various things
site_author: Nicholas Wilde
site_url: https://nicholaswilde.io/notes
copyright: Copyright &copy; 2024 Nicholas Wilde
dev_addr: '0.0.0.0:8000'

# Repository
repo_name: nicholaswilde/notes
repo_url: https://github.com/nicholaswilde/notes
edit_uri: "edit/main/docs/"

# Page tree
nav:
  - Home: index.md
  - Ansible: ansible.md
  - Apps: apps.md
  - Arch: arch.md
  - Bash: bash.md
  - Bitwarden: bitwarden.md
  - Chrome OS: chromeos.md
  - Deprecation: deprecation.md
  - Docker: docker.md
  - ESPHome: esphome.md
  - Flux: flux.md
  - Git: git.md
  - Github Actions: github-actions.md
  - Go: go.md
  - GPG: gpg.md
  - Helm: helm.md
  - Home Assistant: home-assistant.md
  - Homelab: homelab.md
  - Images: images.md
  - Kind: kind.md
  - Kubernetes: kubernetes.md
  - LastPass: lastpass.md
  - Make: make.md
  - Markdown: markdown.md
  - Micro: micro.md
  - Misc: misc.md
  - Multipass: multipass.md
  - NFS: nfs.md
  - NPM: npm.md
  - Proxmox: proxmox.md
  - Python: python.md
  - Regex: regex.md
  - RPi: rpi.md
  - Signal: signal.md
  - Specifications: specifications.md
  - SSH: ssh.md
  - Task: task.md
  - Ubuntu: ubuntu.md
  - Windows 11: w11.md
  - yq: yq.md
  - Yubikey: yubikey.md
  - Archive:
      - Bitwarden: bitwarden.md
      - Chezmoi: chezmoi.md
      - pass: pass.md

extra:
  social:
    - icon: fontawesome/solid/house
      link: https://nicholaswilde.io/
    - icon: fontawesome/brands/github
      link: https://github.com/nicholaswilde
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/nicholascwilde
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/wildewoodworking/
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/in/nicholaswilde
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/nicholas.wilde/
    - icon: fontawesome/brands/keybase
      link: https://keybase.io/nicholaswilde
    - icon: fontawesome/solid/key
      link: https://github.com/nicholaswilde.gpg


theme:
  name: material
  language: en
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.top
    - navigation.tracking
    - navigation.footer
    - content.code.copy
    - content.action.edit
    - content.action.view
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search
  - tags
  - minify:
      minify_html: true

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: nicholaswilde
      repo: notes
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
