---
version: '3'

vars:
  PORT: 8000

tasks:
  build:
    desc: Build documentation using zensical
    cmds:
      - uv run zensical build

  up:
    desc: Start server
    cmds:
      - task: serve

  serve:
    desc: >-
      Start development server on http://0.0.0.0:{{ .PORT }} using
      zensical
    cmds:
      - >-
        uv run zensical serve --dev-addr 0.0.0.0:{{ .PORT }}
    deps:
      - build

  linkcheck:
    desc: Run markdown-link-check
    cmds:
      - ./scripts/linkcheck.sh
    ignore_error: true

  lint:
    desc: Lint the project
    deps:
      - yamllint
      - markdownlint
      - linkcheck
    ignore_error: true

  markdownlint:
    desc: Run markdownlint-cli
    cmds:
      - >-
        docker run --rm -v ${PWD}:/markdown:ro
        06kellyjac/markdownlint-cli .
    ignore_error: true

  yamllint:
    desc: Run yamllint
    cmds:
      - uv run yamllint .
    ignore_error: true

  default:
    cmds:
      - task -l
    silent: true
